kind = "mobile"
previewPath = "/zeus-mob-app/"
title = "ZEUS MOB"
version = "1.0.0"
id = "artifacts/zeus-mob-app"
router = "expo-domain"

[[integratedSkills]]
name = "expo"
version = "1.0.0"

[[services]]
ensurePreviewReachable = "/status"
name = "expo"
paths = [ "/zeus-mob-app/" ]
localPort = 23906

[services.development]
run = "pnpm --filter @workspace/zeus-mob-app run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/zeus-mob-app", "run", "build" ]
run = [ "pnpm", "--filter", "@workspace/zeus-mob-app", "run", "serve" ]

[services.env]
PORT = "23906"
BASE_PATH = "/zeus-mob-app/"
